# Generated by Django 3.0.6 on 2020-07-02 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_auto_20200702_1001'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создание')),
                ('number', models.TextField(verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Оплата услуги пользователя',
                'verbose_name_plural': 'Оплата услуг пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создание')),
                ('number', models.TextField(verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Оплата услуги пользователя',
                'verbose_name_plural': 'Оплата услуг пользователя',
            },
        ),
        migrations.RemoveField(
            model_name='projectpaidfeature',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='userspaidfeature',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='payments.UsersPaidFeature', verbose_name='Платная услуга'),
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.PaidFeatureType', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='projecttransaction',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='payments.ProjectPaidFeature', verbose_name='Платная услуга'),
        ),
        migrations.AddField(
            model_name='projecttransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_features', to='main.Project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projecttransaction',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.PaidFeatureType', verbose_name='Тип'),
        ),
    ]
