# Generated by Django 3.0.6 on 2020-07-02 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200702_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttransaction',
            name='sum',
            field=models.FloatField(default=None, verbose_name='Сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='sum',
            field=models.FloatField(default=None, verbose_name='Сумма'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectLinkedPaidFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_paid_feature_1', to='payments.ProjectPaidFeature', verbose_name='Связаная услуга проекта 1')),
                ('main_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_paid_features', to='payments.ProjectPaidFeature', verbose_name='Основная услуга проекта')),
                ('second_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_paid_feature_2', to='payments.ProjectPaidFeature', verbose_name='Связаная услуга проекта 2')),
            ],
            options={
                'verbose_name': 'Связаные платные услуги',
                'verbose_name_plural': 'Связаные платные услуги',
            },
        ),
    ]
