# Generated by Django 3.0.6 on 2020-07-02 07:11

from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200702_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlinkedpaidfeatures',
            name='first_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_paid_feature_1', to='payments.PaidFeatureType', validators=[payments.models.is_top], verbose_name='Связаная топ услуга'),
        ),
        migrations.AlterField(
            model_name='projectlinkedpaidfeatures',
            name='main_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_paid_features', to='payments.PaidFeatureType', validators=[payments.models.is_top_detailed], verbose_name='Основная услуга проекта'),
        ),
        migrations.AlterField(
            model_name='projectlinkedpaidfeatures',
            name='second_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_paid_feature_2', to='payments.PaidFeatureType', validators=[payments.models.is_detailed], verbose_name='Связаная выделеная услуга'),
        ),
    ]
