# Generated by Django 3.0.6 on 2020-07-02 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200702_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttransaction',
            name='succeeded',
            field=models.BooleanField(blank=True, default=False, verbose_name='Завершенная'),
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='succeeded',
            field=models.BooleanField(blank=True, default=False, verbose_name='Завершенная'),
        ),
        migrations.AlterField(
            model_name='projecttransaction',
            name='feature',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='payments.ProjectPaidFeature', verbose_name='Платная услуга'),
        ),
    ]
