# Generated by Django 3.0.6 on 2020-07-02 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20200702_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttransaction',
            name='feature',
        ),
        migrations.AddField(
            model_name='projecttransaction',
            name='feature_main',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_as_first', to='payments.ProjectPaidFeature', verbose_name='Платная услуга'),
        ),
        migrations.AddField(
            model_name='projecttransaction',
            name='feature_secondary',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_as_second', to='payments.ProjectPaidFeature', verbose_name='Платная услуга'),
        ),
    ]
