# Generated by Django 3.0.6 on 2020-07-03 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200702_1001'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0008_auto_20200702_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создание')),
                ('number', models.TextField(verbose_name='Номер')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('succeeded', models.BooleanField(blank=True, default=False, verbose_name='Завершенная')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Для пользователя'), (2, 'Для проекта')], default=1, verbose_name='Тип')),
                ('feature_main', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_as_first', to='payments.ProjectPaidFeature', verbose_name='Платная услуга')),
                ('feature_secondary', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_as_second', to='payments.ProjectPaidFeature', verbose_name='Платная услуга')),
                ('feature_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.PaidFeatureType', verbose_name='Тип')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.Project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оплата услуги пользователя',
                'verbose_name_plural': 'Оплата услуг пользователя',
            },
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='type',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProjectTransaction',
        ),
        migrations.DeleteModel(
            name='UserTransaction',
        ),
    ]
