# Generated by Django 3.0.6 on 2020-07-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20200703_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='creation_date',
        ),
    ]
