# Generated by Django 3.0.6 on 2020-07-03 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20200703_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='number',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='feature_main',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_as_first', to='payments.ProjectPaidFeature', verbose_name='Основная платная услуга'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='feature_secondary',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_as_second', to='payments.ProjectPaidFeature', verbose_name='Вторая платная услуга'),
        ),
    ]
