# Generated by Django 3.0.6 on 2020-07-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20200703_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='project_feature_main',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_as_first', to='payments.ProjectPaidFeature', verbose_name='Основная платная услуга проекта'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project_feature_secondary',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_as_second', to='payments.ProjectPaidFeature', verbose_name='Вторая платная услуга проекта'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_feature',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_as_users', to='payments.UsersPaidFeature', verbose_name='Платная услуга пользователя'),
        ),
    ]
