# Generated by Django 3.0.6 on 2020-06-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formanswer',
            old_name='order',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='formquestion',
            old_name='order',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='formquestiongroup',
            old_name='order',
            new_name='position',
        ),
    ]
