# Generated by Django 3.0.6 on 2020-06-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200612_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanswer',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='formquestiongroup',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция'),
        ),
    ]
