# Generated by Django 3.0.6 on 2020-06-18 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_mainuser_creation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_auto_20200612_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Создана'), (2, 'Принята'), (3, 'Завершена (не подтверждено)'), (4, 'Завершена'), (5, 'Отклонена клиентом'), (6, 'Отклонена специалистом')], default=1, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Комментарий')),
                ('rating', models.PositiveSmallIntegerField(null=True, verbose_name='Рейтинг')),
                ('decline_reason', models.CharField(max_length=1000, null=True, verbose_name='Причина отказа')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='users.ProjectCategory', verbose_name='Категория')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_applications', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merchant_applications', to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=utils.upload.application_document_path, validators=[utils.validators.basic_validate_images, utils.validators.validate_file_size], verbose_name='Документ')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.Application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Документ заявки',
                'verbose_name_plural': 'Документы заявок',
            },
        ),
    ]
