# Generated by Django 3.0.6 on 2020-06-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200618_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='application',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
