# Generated by Django 3.0.6 on 2020-06-19 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200603_1655'),
        ('profiles', '0006_auto_20200618_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='main.Project', verbose_name='Проект'),
        ),
    ]
