# Generated by Django 3.0.6 on 2020-06-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_notification_paidfeaturetype_projectpaidfeature_transaction_userspaidfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidfeaturetype',
            name='name',
        ),
    ]
