# Generated by Django 3.0.6 on 2020-06-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20200622_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpaidfeature',
            name='refreshed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Продлен'),
        ),
        migrations.AddField(
            model_name='userspaidfeature',
            name='refreshed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Продлен'),
        ),
    ]
