# Generated by Django 3.0.6 on 2020-06-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200624_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paidfeaturetype',
            options={'ordering': ('position',), 'verbose_name': 'Тип платной услуги', 'verbose_name_plural': 'Типы платных услуг'},
        ),
        migrations.AddField(
            model_name='paidfeaturetype',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='paidfeaturetype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Про аккаунт'), (2, 'Топ проект'), (3, 'Выделеный проект'), (3, 'Топ и Выделеный проект')], default=1, verbose_name='Тип'),
        ),
    ]
