# Generated by Django 3.0.6 on 2020-06-24 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200624_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidfeaturetype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Про аккаунт'), (2, 'Топ проект'), (3, 'Выделеный проект'), (4, 'Топ и Выделеный проект')], default=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='projectpaidfeature',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.PaidFeatureType', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='userspaidfeature',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.PaidFeatureType', verbose_name='Тип'),
        ),
    ]
