# Generated by Django 3.0.6 on 2020-06-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20200624_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpaidfeature',
            name='refreshed',
        ),
        migrations.RemoveField(
            model_name='userspaidfeature',
            name='refreshed',
        ),
        migrations.AddField(
            model_name='projectpaidfeature',
            name='refresh_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество продлений'),
        ),
        migrations.AddField(
            model_name='userspaidfeature',
            name='refresh_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество продлений'),
        ),
    ]
