# Generated by Django 3.0.6 on 2020-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20200624_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
