# Generated by Django 3.0.6 on 2020-06-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_notification_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-creation_date',), 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
    ]
