# Generated by Django 3.0.6 on 2020-07-02 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20200625_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpaidfeature',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectpaidfeature',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='projectpaidfeature',
            name='type',
        ),
        migrations.RemoveField(
            model_name='userspaidfeature',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='userspaidfeature',
            name='type',
        ),
        migrations.RemoveField(
            model_name='userspaidfeature',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaidFeatureType',
        ),
        migrations.DeleteModel(
            name='ProjectPaidFeature',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UsersPaidFeature',
        ),
    ]
