# Generated by Django 3.0.6 on 2020-07-06 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0018_auto_20200702_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_applications', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='application',
            name='merchant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merchant_applications', to=settings.AUTH_USER_MODEL, verbose_name='Специалист'),
        ),
    ]
