# Generated by Django 3.0.6 on 2020-07-06 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200706_1954'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_auto_20200706_1954'),
        ('profiles', '0020_auto_20200706_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='users.ProjectCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='application',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_applications', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='application',
            name='merchant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_applications', to=settings.AUTH_USER_MODEL, verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='application',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='main.Project', verbose_name='Проект'),
        ),
    ]
