# Generated by Django 3.0.6 on 2020-08-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20200706_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
