# Generated by Django 3.0.6 on 2020-08-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20200812_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
