# Generated by Django 3.0.6 on 2020-05-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPurposeSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Подип назначения',
                'verbose_name_plural': 'Подтипы назначений',
            },
        ),
        migrations.CreateModel(
            name='ProjectPurposeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип назначения',
                'verbose_name_plural': 'Типы назначений',
            },
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='projectpurpose',
            options={'verbose_name': 'Назначение', 'verbose_name_plural': 'Назначения'},
        ),
        migrations.AlterModelOptions(
            name='projectstyle',
            options={'verbose_name': 'Стиль', 'verbose_name_plural': 'Стили'},
        ),
        migrations.AlterModelOptions(
            name='projecttag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='merchant_profiles', to='users.ProjectTag', verbose_name='Тэги'),
        ),
    ]
