# Generated by Django 3.0.6 on 2020-05-21 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200521_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpurpose',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purposes', to='users.ProjectPurposeSubType', verbose_name='Подтип'),
        ),
        migrations.AddField(
            model_name='projectpurpose',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purposes', to='users.ProjectPurposeType', verbose_name='Тип'),
        ),
    ]
