# Generated by Django 3.0.6 on 2020-05-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200521_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivation',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CLIENT'), (2, 'MERCHANT')], default=1, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
    ]
