# Generated by Django 3.0.6 on 2020-05-22 08:46

from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200521_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Project category', 'verbose_name_plural': 'Project categories'},
        ),
        migrations.AlterModelOptions(
            name='projectpurposesubtype',
            options={'verbose_name': 'purpose subtype', 'verbose_name_plural': 'purpose subtypes'},
        ),
        migrations.AddField(
            model_name='projecttag',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='users.ProjectCategory', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialization',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='users.ProjectCategory', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=utils.upload.project_category_image_path, validators=[utils.validators.basic_validate_images, utils.validators.validate_file_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
