# Generated by Django 3.0.6 on 2020-05-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200522_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='specializations',
            field=models.ManyToManyField(null=True, related_name='merchant_profiles', to='users.Specialization', verbose_name='Специалиация'),
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='category',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='category',
            field=models.ManyToManyField(null=True, related_name='merchant_profiles', to='users.ProjectCategory', verbose_name='Категория'),
        ),
    ]
