# Generated by Django 3.0.6 on 2020-05-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200522_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantprofile',
            old_name='category',
            new_name='categories',
        ),
    ]
