# Generated by Django 3.0.6 on 2020-05-25 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200525_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='phone',
        ),
        migrations.CreateModel(
            name='MerchantPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(help_text='Номер телефона', max_length=31)),
                ('is_valid', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('user', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефона',
            },
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='phone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='users.MerchantPhone', verbose_name='Номер телефона'),
        ),
    ]
