# Generated by Django 3.0.6 on 2020-05-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200525_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantphone',
            name='phone',
            field=models.CharField(max_length=8, verbose_name='Номер телефона'),
        ),
    ]
