# Generated by Django 3.0.6 on 2020-05-26 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200525_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Клиент'), (2, 'Специалист')], default=1, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='merchantphone',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Клиент'), (2, 'Специалист')], default=1, verbose_name='Роль'),
        ),
    ]
