# Generated by Django 3.0.6 on 2020-05-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200526_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Рейтинг'),
        ),
    ]
