# Generated by Django 3.0.6 on 2020-05-29 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200529_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('text', models.CharField(max_length=500, verbose_name='Основной текст')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('user_likes', models.ManyToManyField(related_name='reviews_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Основной текст')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='users.MerchantReview', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Ответ на отзыв',
                'verbose_name_plural': 'Ответы на отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReviewDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=utils.upload.review_document_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Документ')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.MerchantReview', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Фото отзыва',
                'verbose_name_plural': 'Фото отзывов',
            },
        ),
    ]
