# Generated by Django 3.0.6 on 2020-05-29 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merchantreview_reviewdocument_reviewreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantreview',
            name='likes_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество лайков'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='likes_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество лайков'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='user_likes',
            field=models.ManyToManyField(related_name='reply_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='merchantreview',
            name='user_likes',
            field=models.ManyToManyField(related_name='reviews_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи лайки'),
        ),
    ]
