# Generated by Django 3.0.6 on 2020-05-29 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200529_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantreview',
            name='user_likes',
            field=models.ManyToManyField(blank=True, related_name='reviews_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи лайки'),
        ),
    ]
