# Generated by Django 3.0.6 on 2020-06-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200529_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantprofile',
            old_name='pro',
            new_name='is_pro',
        ),
    ]
