# Generated by Django 3.0.6 on 2020-06-03 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_reviewreply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='user_likes',
            field=models.ManyToManyField(blank=True, related_name='reply_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
