# Generated by Django 3.0.6 on 2020-06-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200605_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Номер телефона'),
        ),
    ]
