# Generated by Django 3.0.6 on 2020-06-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_clientprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
