# Generated by Django 3.0.6 on 2020-06-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200609_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpurposesubtype',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='users.ProjectPurposeType', verbose_name='Тип'),
        ),
    ]
