# Generated by Django 3.0.6 on 2020-06-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_projectpurposesubtype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='phone',
        ),
    ]
