# Generated by Django 3.0.6 on 2020-06-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_clientprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата регистрации'),
        ),
    ]
