# Generated by Django 3.0.6 on 2020-06-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_mainuser_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainuser',
            options={'ordering': ['-id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
