# Generated by Django 3.0.6 on 2020-06-19 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20200618_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_client_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Рейтинг клиента',
                'verbose_name_plural': 'Рейтинги клиентов',
            },
        ),
    ]
