# Generated by Django 3.0.6 on 2020-06-24 12:19

from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_clientrating_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReplyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=utils.upload.review_reply_document_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Документ')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.ReviewReply', verbose_name='Ответ на отзыв')),
            ],
            options={
                'verbose_name': 'Фото ответа на отзыв',
                'verbose_name_plural': 'Фото ответов на отзывы',
            },
        ),
    ]
