# Generated by Django 3.0.6 on 2020-06-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_reviewreplydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantreview',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='merchantreview',
            name='rating',
            field=models.FloatField(blank=True, default=0, verbose_name='Рейтинг'),
        ),
    ]
