# Generated by Django 3.0.6 on 2020-07-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20200626_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_profiles', to='users.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='projectpurpose',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purposes', to='users.ProjectPurposeSubType', verbose_name='Подтип'),
        ),
        migrations.AlterField(
            model_name='projectpurpose',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purposes', to='users.ProjectPurposeType', verbose_name='Тип'),
        ),
    ]
