# Generated by Django 3.0.6 on 2020-05-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=5000, verbose_name='Ответ')),
                ('position', models.IntegerField(verbose_name='Позиция')),
            ],
        ),
    ]
