# Generated by Django 3.0.6 on 2020-08-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_mailing_mailingrecipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingrecipient',
            options={'verbose_name': 'Получатель рассылки', 'verbose_name_plural': 'Получатели рассылки'},
        ),
    ]
