# Generated by Django 3.0.6 on 2020-08-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0004_auto_20200812_1247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mailing',
        ),
        migrations.DeleteModel(
            name='MailingRecipient',
        ),
    ]
