# Generated by Django 3.0.6 on 2020-05-29 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_auto_20200529_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                ('text', models.CharField(max_length=10000, verbose_name='Основоной текст')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('is_main', models.BooleanField(blank=True, default=False, verbose_name='На главной')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='BlogPostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блога',
            },
        ),
        migrations.CreateModel(
            name='PostDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=utils.upload.blog_post_document_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Документ')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='blog.BlogPost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Документ блога',
                'verbose_name_plural': 'Документы блога',
            },
        ),
        migrations.CreateModel(
            name='MainPageBlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_page', to='blog.BlogPost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Пост на главной странице',
                'verbose_name_plural': 'Посты на главной странице',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_posts', to='blog.BlogPostCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_posts', to='users.City', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='user_likes',
            field=models.ManyToManyField(related_name='blog_post_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки пользователей'),
        ),
    ]
