# Generated by Django 3.0.6 on 2020-06-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200609_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpageblogpost',
            options={'ordering': ('position',), 'verbose_name': 'Пост на главной странице', 'verbose_name_plural': 'Посты на главной странице'},
        ),
        migrations.AddField(
            model_name='mainpageblogpost',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
