# Generated by Django 3.0.6 on 2020-07-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200706_1954'),
        ('blog', '0003_auto_20200626_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='blog.BlogPostCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='users.City', verbose_name='Город'),
        ),
    ]
