# Generated by Django 3.0.6 on 2020-05-28 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_auto_20200526_1414'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                ('text', models.CharField(max_length=10000, verbose_name='Основоной текст')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='BlogPostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блога',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('price_from', models.FloatField(verbose_name='Цена от')),
                ('price_to', models.FloatField(verbose_name='Цена до')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('is_top', models.BooleanField(default=False, verbose_name='Топ')),
                ('is_detailed', models.BooleanField(default=False, verbose_name='Выделенный')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main', to='users.ProjectCategory', verbose_name='Категория')),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main', to='users.ProjectPurpose', verbose_name='Назначение')),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main', to='users.ProjectStyle', verbose_name='Стиль')),
                ('tags', models.ManyToManyField(related_name='main', to='users.ProjectTag', verbose_name='Тэги')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main', to='users.ProjectType', verbose_name='Тип')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('users_favorites', models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи избранное')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Render360',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=utils.upload.profile_document_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Документ')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='render360', to='main.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фото 360 проекта',
                'verbose_name_plural': 'Фото 360 проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=utils.upload.profile_document_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Документ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фото проекта',
                'verbose_name_plural': 'Фото проектов',
            },
        ),
        migrations.CreateModel(
            name='PostDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=utils.upload.blog_post_document_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Документ')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.BlogPost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Документ блога',
                'verbose_name_plural': 'Документы блога',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_posts', to='main.BlogPostCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='user_likes',
            field=models.ManyToManyField(related_name='blog_post_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки пользователей'),
        ),
    ]
