# Generated by Django 3.0.6 on 2020-05-29 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.FloatField(blank=True, default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users_favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи избранное'),
        ),
    ]
