# Generated by Django 3.0.6 on 2020-05-29 05:54

from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200529_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='document',
            field=models.FileField(upload_to=utils.upload.project_document_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Документ'),
        ),
        migrations.CreateModel(
            name='MainPageBlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_page', to='main.BlogPost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Пост на главной странице',
                'verbose_name_plural': 'Посты на главной странице',
            },
        ),
    ]
