# Generated by Django 3.0.6 on 2020-05-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merchantreview_reviewdocument_reviewreply'),
        ('main', '0003_auto_20200529_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_posts', to='users.City', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, verbose_name='На главной'),
        ),
    ]
