# Generated by Django 3.0.6 on 2020-05-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200529_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpageblogpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postdocument',
            name='post',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='BlogPostCategory',
        ),
        migrations.DeleteModel(
            name='MainPageBlogPost',
        ),
        migrations.DeleteModel(
            name='PostDocument',
        ),
    ]
