# Generated by Django 3.0.6 on 2020-06-02 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20200601_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, default=0, verbose_name='Рейтинг')),
                ('text', models.CharField(max_length=1000, verbose_name='Основной текст')),
                ('creation_date', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_likes', models.ManyToManyField(blank=True, related_name='project_comments_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий проекта',
                'verbose_name_plural': 'Комментарии проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='main.Project', verbose_name='Пользователь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр проета',
                'verbose_name_plural': 'Просмотры проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Основной текст')),
                ('creation_date', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='main.ProjectComment', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий пректа',
                'verbose_name_plural': 'Комментарии пректов',
            },
        ),
        migrations.CreateModel(
            name='ProjectCommentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=utils.upload.project_comment_document_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Документ')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.ProjectComment', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Документ комментария',
                'verbose_name_plural': 'Документы комментариев',
            },
        ),
    ]
