# Generated by Django 3.0.6 on 2020-06-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200602_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='likes_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата'),
        ),
    ]
