# Generated by Django 3.0.6 on 2020-06-02 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20200602_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcommentreply',
            name='likes_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество лайков'),
        ),
        migrations.AddField(
            model_name='projectcommentreply',
            name='user_likes',
            field=models.ManyToManyField(blank=True, related_name='project_comments_reply_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки пользователь'),
        ),
        migrations.CreateModel(
            name='ProjectComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Причина')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='main.Project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жалоба на проект',
                'verbose_name_plural': 'Жалобы на проекты',
            },
        ),
    ]
