# Generated by Django 3.0.6 on 2020-06-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_projectcommentreply_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcommentreply',
            options={'verbose_name': 'Ответ на комментарий проекта', 'verbose_name_plural': 'Ответы на комментарии пректов'},
        ),
    ]
