# Generated by Django 3.0.6 on 2020-06-23 07:06

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200603_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='render360',
            name='document',
            field=models.FileField(upload_to=utils.upload.project_render360_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Документ'),
        ),
    ]
