# Generated by Django 3.0.6 on 2020-06-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200623_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='render360',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='render360', to='main.Project', verbose_name='Проект'),
        ),
    ]
