# Generated by Django 3.0.6 on 2020-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200623_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='to_profile_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Переходы в профиль'),
        ),
    ]
