# Generated by Django 3.0.6 on 2020-06-25 09:31

from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_project_to_profile_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCommentReplyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=utils.upload.project_comment_reply_document_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Документ')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.ProjectCommentReply', verbose_name='Ответ на комментарий')),
            ],
            options={
                'verbose_name': 'Документ ответа на комментарий',
                'verbose_name_plural': 'Документы ответов на комментарии',
            },
        ),
    ]
