# Generated by Django 3.0.6 on 2020-06-30 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20200626_2105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_projectcommentreplydocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Причина')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Активная')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='main.ProjectComment', verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жалоба на комментарий',
                'verbose_name_plural': 'Жалобы на комментарии',
            },
        ),
        migrations.CreateModel(
            name='ProjectComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Причина')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Активная')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='main.Project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жалоба на проект',
                'verbose_name_plural': 'Жалобы на проекты',
            },
        ),
        migrations.CreateModel(
            name='ReviewComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Причина')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Активная')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='users.MerchantReview', verbose_name='Отзыв')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жалоба на отзыв',
                'verbose_name_plural': 'Жалобы на отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReviewReplyComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Причина')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Активная')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='users.ReviewReply', verbose_name='Ответ на отзыв')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жалоба на ответ на отзыв',
                'verbose_name_plural': 'Жалобы на ответы на отзывы',
            },
        ),
        migrations.DeleteModel(
            name='ProjectComplaint',
        ),
    ]
