# Generated by Django 3.0.6 on 2020-06-30 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_auto_20200630_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReplyComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Причина')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Активная')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='main.ProjectCommentReply', verbose_name='Ответ на комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жалоба на ответ на комментарий',
                'verbose_name_plural': 'Жалобы на ответы на комментарии',
            },
        ),
    ]
