# Generated by Django 3.0.6 on 2020-07-02 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_commentreplycomplain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentcomplain',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Жалоба на комментарий', 'verbose_name_plural': 'Жалобы на комментарии'},
        ),
        migrations.AlterModelOptions(
            name='commentreplycomplain',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Жалоба на ответ на комментарий', 'verbose_name_plural': 'Жалобы на ответы на комментарии'},
        ),
        migrations.AlterModelOptions(
            name='projectcomplain',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Жалоба на проект', 'verbose_name_plural': 'Жалобы на проекты'},
        ),
        migrations.AlterModelOptions(
            name='reviewcomplain',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Жалоба на отзыв', 'verbose_name_plural': 'Жалобы на отзывы'},
        ),
        migrations.AlterModelOptions(
            name='reviewreplycomplain',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Жалоба на ответ на отзыв', 'verbose_name_plural': 'Жалобы на ответы на отзывы'},
        ),
    ]
