# Generated by Django 3.0.6 on 2020-07-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200706_1954'),
        ('main', '0020_auto_20200702_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main', to='users.ProjectCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='project',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main', to='users.ProjectPurpose', verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main', to='users.ProjectStyle', verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main', to='users.ProjectType', verbose_name='Тип'),
        ),
    ]
